name: Build React Native APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_DIR: MyNewApp
  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64
  NODE_VERSION: 22.17.0

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd $PROJECT_DIR
        npm install

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses
      shell: bash

    - name: Build Release APK
      run: |
        cd $PROJECT_DIR/android
        chmod +x ./gradlew
        ./gradlew :app:clean
        ./gradlew :app:assembleRelease --stacktrace

    - name: Check APK exists
      run: |
        if [ ! -f "$PROJECT_DIR/android/app/build/outputs/apk/release/app-release.apk" ]; then
          echo "APK not found!"
          exit 1
        else
          echo "APK found."
        fi

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: $PROJECT_DIR/android/app/build/outputs/apk/release/app-release.apk
        if-no-files-found: error
