name: Build React Native APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_DIR: MyNewApp
  JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.16-8/x64

jobs:
  build-apk:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.17.0
          cache: "npm"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.PROJECT_DIR }}

      # 4️⃣ Setup JDK (already set JAVA_HOME in env)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 5️⃣ Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 36
          build-tools: 36.0.0
          ndk: 27.1.12297006

      # 6️⃣ Grant gradlew execute permission
      - name: Make gradlew executable
        run: chmod +x ${{ env.PROJECT_DIR }}/android/gradlew

      # 7️⃣ Build APK
      - name: Build Release APK
        run: ./gradlew assembleRelease
        working-directory: ${{ env.PROJECT_DIR }}/android

      # 8️⃣ Verify APK exists
      - name: Verify APK
        run: |
          if [ ! -f ${{ env.PROJECT_DIR }}/android/app/build/outputs/apk/release/app-release.apk ]; then
            echo "APK not found!"
            exit 1
          fi

      # 9️⃣ Upload artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: ${{ env.PROJECT_DIR }}/android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
